"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-10 22:17:55.308584+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('card_variants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_variants')),
    sa.UniqueConstraint('code', name=op.f('uq_card_variants_code'))
    )
    op.create_table('collection_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=24), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('folder', 'watchlist', 'smart')", name=op.f('ck_collection_groups_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_collection_groups_name'))
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('provider_class', sa.String(length=120), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key_env_var', sa.String(length=80), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('terms_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('market_data', 'card_catalog', 'manual', 'csv_import')", name=op.f('ck_data_sources_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_data_sources_code'))
    )
    op.create_table('grading_companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('market_recognition_score', sa.Float(), nullable=False),
    sa.Column('grade_scale_max', sa.Float(), nullable=False),
    sa.Column('supports_half_grades', sa.Boolean(), nullable=False),
    sa.Column('supports_subgrades', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_companies')),
    sa.UniqueConstraint('code', name=op.f('uq_grading_companies_code'))
    )
    op.create_table('selling_cost_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=48), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('payment_fee_pct', sa.Float(), nullable=False),
    sa.Column('payment_fixed_fee_minor', sa.Integer(), nullable=False),
    sa.Column('listing_fee_minor', sa.Integer(), nullable=False),
    sa.Column('other_fee_pct', sa.Float(), nullable=False),
    sa.Column('fees_apply_to_shipping', sa.Boolean(), nullable=False),
    sa.Column('shipping_charged_to_buyer_minor', sa.Integer(), nullable=False),
    sa.Column('shipping_cost_minor', sa.Integer(), nullable=False),
    sa.Column('packaging_cost_minor', sa.Integer(), nullable=False),
    sa.Column('graded_shipping_cost_minor', sa.Integer(), nullable=True),
    sa.Column('graded_packaging_cost_minor', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selling_cost_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_selling_cost_profiles_code'))
    )
    op.create_table('sets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('series', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('total_cards', sa.Integer(), nullable=True),
    sa.Column('secret_cards', sa.Integer(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("language IN ('English', 'Japanese', 'German', 'French', 'Italian', 'Spanish', 'Portuguese', 'Korean', 'Chinese', 'Dutch', 'Polish', 'Russian', 'Thai', 'Indonesian', 'Other')", name=op.f('ck_sets_language_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sets')),
    sa.UniqueConstraint('code', 'language', name='uq_sets_code_language')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sets_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sets_name'), ['name'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('set_id', sa.String(length=32), nullable=True),
    sa.Column('set_name', sa.String(length=160), nullable=True),
    sa.Column('set_code', sa.String(length=32), nullable=True),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('variant_id', sa.String(length=32), nullable=True),
    sa.Column('variant', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('printing', sa.String(length=48), nullable=True),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('pokemon', sa.String(length=120), nullable=True),
    sa.Column('card_type', sa.String(length=64), nullable=True),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('catalog_key', sa.String(length=200), nullable=True),
    sa.Column('raw_condition', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price_minor', sa.Integer(), nullable=True),
    sa.Column('purchase_currency', sa.String(length=3), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('user_raw_value_minor', sa.Integer(), nullable=True),
    sa.Column('decision_override', sa.String(length=32), nullable=True),
    sa.Column('decision_override_reason', sa.Text(), nullable=True),
    sa.Column('review_after', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision_override IS NULL OR decision_override IN ('grade', 'grade_if_batch_filled', 'sell_raw', 'keep_raw', 'hold', 'do_not_grade', 'insufficient_data')", name=op.f('ck_cards_decision_override_valid')),
    sa.CheckConstraint("language IN ('English', 'Japanese', 'German', 'French', 'Italian', 'Spanish', 'Portuguese', 'Korean', 'Chinese', 'Dutch', 'Polish', 'Russian', 'Thai', 'Indonesian', 'Other')", name=op.f('ck_cards_language_valid')),
    sa.CheckConstraint("status IN ('in_collection', 'submitted_for_grading', 'graded', 'listed_for_sale', 'sold', 'archived')", name=op.f('ck_cards_status_valid')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_cards_quantity_positive')),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name=op.f('fk_cards_set_id_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['card_variants.id'], name=op.f('fk_cards_variant_id_card_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards'))
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_card_number'), ['card_number'], unique=False)
        batch_op.create_index('ix_cards_catalog_key', ['catalog_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_pokemon'), ['pokemon'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_set_code'), ['set_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_set_name'), ['set_name'], unique=False)
        batch_op.create_index('ix_cards_set_number', ['set_code', 'card_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_variant'), ['variant'], unique=False)

    op.create_table('grade_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('face', sa.String(length=8), nullable=True),
    sa.Column('min_severity', sa.String(length=16), nullable=False),
    sa.Column('max_grade', sa.Float(), nullable=True),
    sa.Column('probability_multiplier', sa.Float(), nullable=True),
    sa.Column('penalty_from_grade', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grade_rules_company_id_grading_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_rules')),
    sa.UniqueConstraint('code', name=op.f('uq_grade_rules_code'))
    )
    op.create_table('grading_memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('annual_fee_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('included_credits', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('user_holds', sa.Boolean(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grading_memberships_company_id_grading_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_memberships')),
    sa.UniqueConstraint('company_id', 'code', name='uq_membership_code')
    )
    with op.batch_alter_table('grading_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_memberships_company_id'), ['company_id'], unique=False)

    op.create_table('grading_tiers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('tier_code', sa.String(length=48), nullable=False),
    sa.Column('tier_name', sa.String(length=80), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('minimum_cards', sa.Integer(), nullable=False),
    sa.Column('maximum_cards', sa.Integer(), nullable=True),
    sa.Column('min_declared_value_minor', sa.Integer(), nullable=True),
    sa.Column('max_declared_value_minor', sa.Integer(), nullable=True),
    sa.Column('turnaround_days', sa.Integer(), nullable=True),
    sa.Column('membership_required', sa.Boolean(), nullable=False),
    sa.Column('membership_discount_pct', sa.Float(), nullable=False),
    sa.Column('additional_fees_minor', sa.Integer(), nullable=False),
    sa.Column('per_card_fees_minor', sa.Integer(), nullable=False),
    sa.Column('declared_value_fee_pct', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('source_checked_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('minimum_cards >= 1', name=op.f('ck_grading_tiers_minimum_cards_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grading_tiers_company_id_grading_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_tiers')),
    sa.UniqueConstraint('company_id', 'tier_code', 'effective_from', name='uq_tier_effective')
    )
    with op.batch_alter_table('grading_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_tiers_company_id'), ['company_id'], unique=False)

    op.create_table('card_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("side IN ('front', 'back', 'detail', 'slab')", name=op.f('ck_card_images_side_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_images_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_images'))
    )
    with op.batch_alter_table('card_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_images_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_images_sha256'), ['sha256'], unique=False)

    op.create_table('collection_group_cards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_collection_group_cards_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['collection_groups.id'], name=op.f('fk_collection_group_cards_group_id_collection_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_group_cards')),
    sa.UniqueConstraint('group_id', 'card_id', name='uq_group_card')
    )
    with op.batch_alter_table('collection_group_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_group_cards_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_group_cards_group_id'), ['group_id'], unique=False)

    op.create_table('condition_assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessor', sa.String(length=24), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('front_centering_left', sa.Float(), nullable=True),
    sa.Column('front_centering_right', sa.Float(), nullable=True),
    sa.Column('front_centering_top', sa.Float(), nullable=True),
    sa.Column('front_centering_bottom', sa.Float(), nullable=True),
    sa.Column('back_centering_left', sa.Float(), nullable=True),
    sa.Column('back_centering_right', sa.Float(), nullable=True),
    sa.Column('back_centering_top', sa.Float(), nullable=True),
    sa.Column('back_centering_bottom', sa.Float(), nullable=True),
    sa.Column('front_corner_tl', sa.String(length=16), nullable=False),
    sa.Column('front_corner_tr', sa.String(length=16), nullable=False),
    sa.Column('front_corner_bl', sa.String(length=16), nullable=False),
    sa.Column('front_corner_br', sa.String(length=16), nullable=False),
    sa.Column('front_edge_condition', sa.String(length=16), nullable=False),
    sa.Column('front_surface_condition', sa.String(length=16), nullable=False),
    sa.Column('front_holo_condition', sa.String(length=16), nullable=False),
    sa.Column('front_scratches', sa.String(length=16), nullable=False),
    sa.Column('front_print_lines', sa.String(length=16), nullable=False),
    sa.Column('front_silvering', sa.String(length=16), nullable=False),
    sa.Column('front_whitening', sa.String(length=16), nullable=False),
    sa.Column('front_dents', sa.String(length=16), nullable=False),
    sa.Column('front_dimpling', sa.String(length=16), nullable=False),
    sa.Column('front_creases', sa.String(length=16), nullable=False),
    sa.Column('front_staining', sa.String(length=16), nullable=False),
    sa.Column('front_misc_defects', sa.String(length=16), nullable=False),
    sa.Column('back_corner_tl', sa.String(length=16), nullable=False),
    sa.Column('back_corner_tr', sa.String(length=16), nullable=False),
    sa.Column('back_corner_bl', sa.String(length=16), nullable=False),
    sa.Column('back_corner_br', sa.String(length=16), nullable=False),
    sa.Column('back_edge_condition', sa.String(length=16), nullable=False),
    sa.Column('back_surface_condition', sa.String(length=16), nullable=False),
    sa.Column('back_holo_condition', sa.String(length=16), nullable=False),
    sa.Column('back_scratches', sa.String(length=16), nullable=False),
    sa.Column('back_print_lines', sa.String(length=16), nullable=False),
    sa.Column('back_silvering', sa.String(length=16), nullable=False),
    sa.Column('back_whitening', sa.String(length=16), nullable=False),
    sa.Column('back_dents', sa.String(length=16), nullable=False),
    sa.Column('back_dimpling', sa.String(length=16), nullable=False),
    sa.Column('back_creases', sa.String(length=16), nullable=False),
    sa.Column('back_staining', sa.String(length=16), nullable=False),
    sa.Column('back_misc_defects', sa.String(length=16), nullable=False),
    sa.Column('front_defect_notes', sa.JSON(), nullable=True),
    sa.Column('back_defect_notes', sa.JSON(), nullable=True),
    sa.Column('front_notes', sa.Text(), nullable=True),
    sa.Column('back_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('centering_score_front', sa.Float(), nullable=True),
    sa.Column('centering_score_back', sa.Float(), nullable=True),
    sa.Column('centering_score', sa.Float(), nullable=True),
    sa.Column('corners_score', sa.Float(), nullable=True),
    sa.Column('edges_score', sa.Float(), nullable=True),
    sa.Column('surface_score', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assessor IN ('user', 'image_model', 'imported')", name=op.f('ck_condition_assessments_assessor_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_condition_assessments_card_id_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_condition_assessments'))
    )
    with op.batch_alter_table('condition_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_condition_assessments_card_id'), ['card_id'], unique=False)
        batch_op.create_index('ix_condition_card_current', ['card_id', 'is_current'], unique=False)

    op.create_table('grading_submissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('tier_id', sa.String(length=32), nullable=True),
    sa.Column('membership_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shipping_out_minor', sa.Integer(), nullable=False),
    sa.Column('shipping_return_minor', sa.Integer(), nullable=False),
    sa.Column('insurance_minor', sa.Integer(), nullable=False),
    sa.Column('membership_allocation_minor', sa.Integer(), nullable=False),
    sa.Column('handling_minor', sa.Integer(), nullable=False),
    sa.Column('other_fees_minor', sa.Integer(), nullable=False),
    sa.Column('cost_allocation_method', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.Date(), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('returned_at', sa.Date(), nullable=True),
    sa.Column('tracking_outbound', sa.String(length=120), nullable=True),
    sa.Column('tracking_return', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cost_allocation_method IN ('equal', 'value_weighted', 'custom')", name=op.f('ck_grading_submissions_cost_allocation_method_valid')),
    sa.CheckConstraint("status IN ('draft', 'planned', 'shipped', 'received', 'grading', 'returned', 'cancelled')", name=op.f('ck_grading_submissions_status_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grading_submissions_company_id_grading_companies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['membership_id'], ['grading_memberships.id'], name=op.f('fk_grading_submissions_membership_id_grading_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tier_id'], ['grading_tiers.id'], name=op.f('fk_grading_submissions_tier_id_grading_tiers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_submissions')),
    sa.UniqueConstraint('reference', name=op.f('uq_grading_submissions_reference'))
    )
    with op.batch_alter_table('grading_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_submissions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_submissions_status'), ['status'], unique=False)

    op.create_table('market_listings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('catalog_key', sa.String(length=200), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('grade_label', sa.String(length=24), nullable=False),
    sa.Column('platform', sa.String(length=48), nullable=True),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shipping_minor', sa.Integer(), nullable=True),
    sa.Column('listing_title', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('seller', sa.String(length=120), nullable=True),
    sa.Column('is_auction', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_market_listings_card_id_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_market_listings_company_id_grading_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_market_listings_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_listings')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_listing_source_external')
    )
    with op.batch_alter_table('market_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_listings_catalog_key'), ['catalog_key'], unique=False)
        batch_op.create_index('ix_market_listings_key_grade', ['catalog_key', 'grade_label'], unique=False)

    op.create_table('market_prices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('catalog_key', sa.String(length=200), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('grade_label', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('median_minor', sa.Integer(), nullable=True),
    sa.Column('weighted_median_minor', sa.Integer(), nullable=True),
    sa.Column('mean_minor', sa.Integer(), nullable=True),
    sa.Column('low_quartile_minor', sa.Integer(), nullable=True),
    sa.Column('high_quartile_minor', sa.Integer(), nullable=True),
    sa.Column('last_sale_minor', sa.Integer(), nullable=True),
    sa.Column('realistic_sale_minor', sa.Integer(), nullable=True),
    sa.Column('quick_sale_minor', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('last_sale_at', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_value_minor', sa.Integer(), nullable=True),
    sa.Column('user_value_note', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence IN ('none', 'low', 'medium', 'high')", name=op.f('ck_market_prices_confidence_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_market_prices_card_id_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_market_prices_company_id_grading_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_market_prices_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_prices')),
    sa.UniqueConstraint('catalog_key', 'grade_label', 'source_id', name='uq_price_key_grade_source')
    )
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_prices_catalog_key'), ['catalog_key'], unique=False)

    op.create_table('market_sales',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('catalog_key', sa.String(length=200), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('grade_label', sa.String(length=24), nullable=False),
    sa.Column('platform', sa.String(length=48), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sale_price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shipping_minor', sa.Integer(), nullable=True),
    sa.Column('condition_note', sa.String(length=120), nullable=True),
    sa.Column('listing_title', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('seller', sa.String(length=120), nullable=True),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('is_auction', sa.Boolean(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=32), nullable=True),
    sa.Column('excluded_by', sa.String(length=16), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("exclusion_reason IS NULL OR exclusion_reason IN ('lot_or_bundle', 'damaged', 'wrong_card', 'wrong_language', 'wrong_variant', 'wrong_grade', 'price_outlier', 'suspected_fake', 'best_offer_unknown', 'user_excluded')", name=op.f('ck_market_sales_exclusion_reason_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_market_sales_card_id_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_market_sales_company_id_grading_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_market_sales_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_sales')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_sale_source_external')
    )
    with op.batch_alter_table('market_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_sales_catalog_key'), ['catalog_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_sales_grade_label'), ['grade_label'], unique=False)
        batch_op.create_index('ix_market_sales_key_grade_date', ['catalog_key', 'grade_label', 'sale_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_sales_sale_date'), ['sale_date'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('catalog_key', sa.String(length=200), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('grade_label', sa.String(length=24), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('value_minor', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('active_listings', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_price_snapshots_card_id_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_price_snapshots_company_id_grading_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_price_snapshots_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_snapshots')),
    sa.UniqueConstraint('catalog_key', 'grade_label', 'snapshot_date', 'source_id', name='uq_snapshot_unique')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_price_snapshots_key_date', ['catalog_key', 'snapshot_date'], unique=False)

    op.create_table('grade_predictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('condition_assessment_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('likely_grade', sa.Float(), nullable=True),
    sa.Column('grade_min', sa.Float(), nullable=True),
    sa.Column('grade_max', sa.Float(), nullable=True),
    sa.Column('max_grade_cap', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('caps_applied', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence IN ('none', 'low', 'medium', 'high')", name=op.f('ck_grade_predictions_confidence_valid')),
    sa.CheckConstraint("kind IN ('physical', 'market')", name=op.f('ck_grade_predictions_kind_valid')),
    sa.CheckConstraint("source IN ('rules_engine', 'user_override', 'calibrated', 'image_model')", name=op.f('ck_grade_predictions_source_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_grade_predictions_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_grade_predictions_company_id_grading_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condition_assessment_id'], ['condition_assessments.id'], name=op.f('fk_grade_predictions_condition_assessment_id_condition_assessments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_predictions'))
    )
    with op.batch_alter_table('grade_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_grade_predictions_card_current', ['card_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_predictions_card_id'), ['card_id'], unique=False)

    op.create_table('submission_cards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('submission_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('tier_id', sa.String(length=32), nullable=True),
    sa.Column('declared_value_minor', sa.Integer(), nullable=True),
    sa.Column('system_declared_value_minor', sa.Integer(), nullable=True),
    sa.Column('declared_value_source', sa.String(length=16), nullable=False),
    sa.Column('declared_value_confidence', sa.String(length=16), nullable=True),
    sa.Column('grading_fee_minor', sa.Integer(), nullable=True),
    sa.Column('allocated_overhead_minor', sa.Integer(), nullable=True),
    sa.Column('predicted_grade', sa.Float(), nullable=True),
    sa.Column('actual_grade', sa.Float(), nullable=True),
    sa.Column('cert_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("declared_value_source IN ('system', 'user')", name=op.f('ck_submission_cards_declared_value_source_valid')),
    sa.CheckConstraint("status IN ('planned', 'submitted', 'graded', 'returned', 'rejected', 'removed')", name=op.f('ck_submission_cards_status_valid')),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_submission_cards_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['grading_submissions.id'], name=op.f('fk_submission_cards_submission_id_grading_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['grading_tiers.id'], name=op.f('fk_submission_cards_tier_id_grading_tiers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_cards')),
    sa.UniqueConstraint('submission_id', 'card_id', name='uq_submission_card')
    )
    with op.batch_alter_table('submission_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_cards_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_cards_submission_id'), ['submission_id'], unique=False)

    op.create_table('prediction_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('grade_prediction_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('submission_id', sa.String(length=32), nullable=True),
    sa.Column('actual_grade', sa.Float(), nullable=False),
    sa.Column('actual_subgrades', sa.JSON(), nullable=True),
    sa.Column('graded_at', sa.Date(), nullable=True),
    sa.Column('cert_number', sa.String(length=64), nullable=True),
    sa.Column('predicted_probabilities', sa.JSON(), nullable=True),
    sa.Column('predicted_likely_grade', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_prediction_results_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['grading_companies.id'], name=op.f('fk_prediction_results_company_id_grading_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_prediction_id'], ['grade_predictions.id'], name=op.f('fk_prediction_results_grade_prediction_id_grade_predictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['grading_submissions.id'], name=op.f('fk_prediction_results_submission_id_grading_submissions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_results'))
    )
    with op.batch_alter_table('prediction_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_results_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_results_card_id'))

    op.drop_table('prediction_results')
    with op.batch_alter_table('submission_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_cards_submission_id'))
        batch_op.drop_index(batch_op.f('ix_submission_cards_card_id'))

    op.drop_table('submission_cards')
    with op.batch_alter_table('grade_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_predictions_card_id'))
        batch_op.drop_index('ix_grade_predictions_card_current')

    op.drop_table('grade_predictions')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_price_snapshots_key_date')

    op.drop_table('price_snapshots')
    with op.batch_alter_table('market_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_sales_sale_date'))
        batch_op.drop_index('ix_market_sales_key_grade_date')
        batch_op.drop_index(batch_op.f('ix_market_sales_grade_label'))
        batch_op.drop_index(batch_op.f('ix_market_sales_catalog_key'))

    op.drop_table('market_sales')
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_prices_catalog_key'))

    op.drop_table('market_prices')
    with op.batch_alter_table('market_listings', schema=None) as batch_op:
        batch_op.drop_index('ix_market_listings_key_grade')
        batch_op.drop_index(batch_op.f('ix_market_listings_catalog_key'))

    op.drop_table('market_listings')
    with op.batch_alter_table('grading_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grading_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_grading_submissions_company_id'))

    op.drop_table('grading_submissions')
    with op.batch_alter_table('condition_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_condition_card_current')
        batch_op.drop_index(batch_op.f('ix_condition_assessments_card_id'))

    op.drop_table('condition_assessments')
    with op.batch_alter_table('collection_group_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_group_cards_group_id'))
        batch_op.drop_index(batch_op.f('ix_collection_group_cards_card_id'))

    op.drop_table('collection_group_cards')
    with op.batch_alter_table('card_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_card_images_card_id'))

    op.drop_table('card_images')
    with op.batch_alter_table('grading_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grading_tiers_company_id'))

    op.drop_table('grading_tiers')
    with op.batch_alter_table('grading_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grading_memberships_company_id'))

    op.drop_table('grading_memberships')
    op.drop_table('grade_rules')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_variant'))
        batch_op.drop_index(batch_op.f('ix_cards_status'))
        batch_op.drop_index('ix_cards_set_number')
        batch_op.drop_index(batch_op.f('ix_cards_set_name'))
        batch_op.drop_index(batch_op.f('ix_cards_set_code'))
        batch_op.drop_index(batch_op.f('ix_cards_pokemon'))
        batch_op.drop_index(batch_op.f('ix_cards_name'))
        batch_op.drop_index('ix_cards_catalog_key')
        batch_op.drop_index(batch_op.f('ix_cards_card_number'))

    op.drop_table('cards')
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sets_name'))
        batch_op.drop_index(batch_op.f('ix_sets_code'))

    op.drop_table('sets')
    op.drop_table('selling_cost_profiles')
    op.drop_table('grading_companies')
    op.drop_table('data_sources')
    op.drop_table('collection_groups')
    op.drop_table('card_variants')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
